documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "README.md"
          - "README-*.md"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - ".pre-commit-config.yaml"
          - ".readthedocs.yaml"
          - "codedev.yml"
