# see https://docs.codecov.com/docs/codecov-yaml
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto
github_checks:
  annotations: false
