# see https://docs.codecov.com/docs/codecov-yaml
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto
comment:
  layout: "diff, files, header, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
github_checks:
  annotations: false
